name: Build macOS App

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build macOS app
      run: |
        pyinstaller build_mac.spec
    
    - name: Create README for distribution
      run: |
        cat > dist/README.txt << 'EOF'
        Component Report Automation - macOS Version
        ============================================
        
        IMPORTANT: Before running the app, you MUST add your credentials.json file!
        
        Instructions:
        1. Right-click on ComponentReportAutomation.app
        2. Select "Show Package Contents"
        3. Navigate to Contents/Resources/
        4. Copy your credentials.json file into this folder
        5. Close the Finder window
        6. Right-click ComponentReportAutomation.app and select "Open"
        7. Click "Open" when macOS shows the security warning
        
        The app is now ready to use!
        
        Note: The first time you open the app, macOS will show a security warning
        because it's not from the App Store. Use the right-click method above.
        EOF
    
    - name: Create distribution package
      run: |
        cd dist
        zip -r ComponentReportAutomation-macOS.zip ComponentReportAutomation.app README.txt
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ComponentReportAutomation-macOS
        path: dist/ComponentReportAutomation-macOS.zip
        retention-days: 30
    
    - name: Create Release (on tag push)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/ComponentReportAutomation-macOS.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}